server:
  http:
    addr: 0.0.0.0:8603
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9603
    timeout: 1s
    etf_addr: "etf-service:9601"
    user_addr: "user-service:9602"
    dtm_addr: "dtm-service:36790"
    local_etf_addr: "127.0.0.1:9601"
    local_user_addr: "127.0.0.1:9602"
    local_dtm_addr: "127.0.0.1:36790"
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password: "123123"
    read_timeout: 0.2s
    write_timeout: 0.2s
